---
title: "Survival simulation"
author: "Uni:jr3755"
date: "February 6, 2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(survival)
```
#Derivation for the quantile function for exponential or Weibull proportional-hazards model

##The hazard function 
$$h_i(a)=
\begin{cases}
\lambda exp(x_i\theta) & \text{Exponential} \\
\lambda\gamma^{\gamma-1} exp(x_i\theta) &\text{Weibull}
\end{cases}
$$

##The survival function 
$$S_i(t)=exp(-\int_{0}^{t}h_i(a)da)=
\begin{cases}
exp(-\int_{0}^{t}\lambda exp(x_i\theta)da)=exp(-exp(x_i\theta)\lambda t) & \text{Exponential} \\
exp(-\int_{0}^{t}\lambda\gamma^{\gamma-1} exp(x_i\theta)da)=exp(-exp(x_i\theta)\lambda t^\gamma) &\text{Weibull}
\end{cases}
$$

##Derivation of the quantile function
$$S(t)=1-F(t) \Rightarrow F(t)=1-S(t) \Rightarrow U=1-S(t) \Rightarrow S(t)=1-U$$

###Exponential
$$exp(-exp(x_i\theta)\lambda t)=1-U\\
\Rightarrow -exp(x_i\theta)\lambda t=log(1-U)\\
\Rightarrow t=\frac{log(U)}{-exp(x_i\theta)\lambda}
$$

###Weibull
$$exp(-exp(x_i\theta)\lambda t^\gamma)=1-U\\
\Rightarrow -exp(x_i\theta)\lambda t^\gamma=log(1-U)\\
\Rightarrow=\sqrt[\gamma] {\frac{log(U)}{-exp(x_i\theta)\lambda}}
$$

#Simulation function for exponential or Weibull
```{r}

# baseline hazard: Weibull

# N = sample size    
# lambda = scale parameter in h0()
# rho = shape parameter in h0()
# beta = fixed effect parameter

simu_data <- function(N, lambda, rho, beta, baseline = "Exponential")
{
  # covariate --> N Bernoulli trials
  x <- sample(x=c(0, 1), size=N, replace=TRUE, prob=c(0.5, 0.5))
  v <- runif(n=N)
  if (baseline == "Exponential") {
    Tlat <- log(v)/(-exp(x * beta) * lambda)}
  else{
    # Weibull latent event times
    Tlat <- (- log(v) / (lambda * exp(x * beta)))^(1 / rho)
  }

  # data set
  data.frame(id=1:N,
             time=Tlat,
             x=x,
             baseline = baseline, stringsAsFactors = FALSE, row.names = NULL)
}
```


```{r}
#Simulation 
set.seed(1234)
sim_num = 100 #Number of simulations
betaHat <- rep(NA, sim_num) #Initial mean beta for each simulation
baseline = "Exponential" #The model for generated data
fitmodel = "Exponential" #The model to fit data
for(k in 1:sim_num)
{
  dat <- simu_data(N=100, lambda=0.01, rho=1, beta=-0.6, baseline = baseline)
  if(fitmodel == "Exponential"){
    fit <- survreg(Surv(time) ~ x, data = dat, dist = "exponential")
    betaHat[k] <- -fit$coefficients[-1]
  } else if(fitmodel == "Cox"){
    fit <- coxph(Surv(time) ~ x, data=dat)
    betaHat[k] <- fit$coef[-1]
  }else{
    fit <- survreg(Surv(time) ~ x, data = dat, dist = "Weibull")
    betaHat[k] <- -fit$coefficients[-1] / fit$scale
  }
}
betaHat #The returned list of mean beta for each simulation
```